# Replace "projectname" and "username"
image: golang:1.14

include:
  - template: Code-Quality.gitlab-ci.yml


variables:
  REPO: github.com
  GROUP: jc01rho
  PROJECT: ogamego_bot
  ARTIFACTS_DIR: artifacts
  BIN_NAME: ogamego_bot
  CUSTOM_PROJECT_DIR: /builds/ogame_golang_bot/ogamego_bot

stages:
  - build
  - test

before_script:
  - mkdir -p $GOPATH/src/$REPO/$GROUP $GOPATH/src/_/builds
  - cp -r $CUSTOM_PROJECT_DIR $GOPATH/src/$REPO/$GROUP/$PROJECT
  - ln -s $GOPATH/src/$REPO/$GROUP $GOPATH/src/_/builds/$GROUP




build-ogamego_bot:
  stage: build
  script:
    - go get -v -d ./...
    - >
      for GOOSV in darwin linux; do
        for GOARCHV in 386 amd64; do
          env GOOS=$GOOSV GOARCH=$GOARCHV go build -v -o $CUSTOM_PROJECT_DIR/${ARTIFACTS_DIR}/ogame-bot-$GOOSV-$GOARCHV
        done
      done
    - >
          for GOOSV in windows; do
            for GOARCHV in 386 amd64; do
              env GOOS=$GOOSV GOARCH=$GOARCHV go build -v -o $CUSTOM_PROJECT_DIR/${ARTIFACTS_DIR}/ogame-bot-$GOOSV-$GOARCHV.exe
            done
          done

  artifacts:
    paths:
      - ${ARTIFACTS_DIR}




test-ogamego_bot:
  stage: test
  script:
    - go test -v -cover ./...
